name: moodle

services:
  postgres:
    image: postgres:16-alpine
    container_name: moodle-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: qwer1234!!
      POSTGRES_DB: moodle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  moodle-app:
    build: .
    container_name: moodle-app
    ports:
      - "80:80"
    environment:
      - MOODLE_DATABASE_HOST=postgres
    volumes:
      - ../:/var/www/html/moodle
      - ../../moodledata:/var/www/moodledata
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
      - postgres

volumes:
  postgres_data:
  moodle_data: